### ISSUE TITLE
min version - too big ?

### ISSUE THREAD

**Issue by leverdeterre** [kciter/qart.js#10]
Hi, thanks to share your nice project.

is it normal to have your qart.min.js size bigger than your qart.js ?

**Comment by kciter** [comment]
Oh.. I will check it.

**Comment by tiaanduplessis** [comment]
@kciter  The issue is the `devtool` property in the Webpack config is set to `inline-source-map`. I've set it to `cheap-module-source-map` and was able to get `qart.min.js ` down from 406 kB to 37.5 kB  and `qart.js` down from 340 kB to 97.4 kB. There are also [other options](https://webpack.github.io/docs/configuration.html#devtool). Would be happy to make a PR

**Comment by kciter** [comment]
@tiaanduplessis Thank you :)
